# Generated by Django 5.2.5 on 2025-10-07 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('deptno', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=20, unique=True)),
                ('loc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField(max_length=10)),
                ('ename', models.CharField()),
                ('job', models.CharField()),
                ('hiredate', models.DateField()),
                ('sal', models.DecimalField(decimal_places=3, max_digits=8)),
                ('comm', models.DecimalField(decimal_places=4, max_digits=8)),
                ('deptno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
                ('mgr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.emp')),
            ],
        ),
    ]
